# Path to a cache directory Used to speed up the split over time by reusing git's objects
cache_url: "/cache/gitsplit"

# Path to the repository to split (default = current path)
project_url: "https://github.com/open-telemetry/opentelemetry-php-contrib.git"

# List of splits.
splits:
  - prefix: "src/MetaPackages/opentelemetry"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/opentelemetry-meta.git"
  - prefix: "src/Aws"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-aws.git"
  - prefix: "src/Symfony"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-sdk-bundle.git"
  - prefix: "src/Instrumentation/CodeIgniter"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-codeigniter.git"
  - prefix: "src/Instrumentation/ExtAmqp"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-ext-amqp.git"
  - prefix: "src/Instrumentation/ExtRdKafka"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-ext-rdkafka.git"
  - prefix: "src/Instrumentation/Guzzle"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-guzzle.git"
  - prefix: "src/Instrumentation/HttpAsyncClient"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-http-async.git"
  - prefix: "src/Instrumentation/IO"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-io.git"
  - prefix: "src/Instrumentation/Laravel"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-laravel.git"
  - prefix: "src/Instrumentation/MongoDB"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-mongodb.git"
  - prefix: "src/Instrumentation/OpenAIPHP"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-openai.git"
  - prefix: "src/Instrumentation/PDO"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-pdo.git"
  - prefix: "src/Instrumentation/Psr3"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-psr3.git"
  - prefix: "src/Instrumentation/Psr6"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-psr6.git"
  - prefix: "src/Instrumentation/Psr14"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-psr14.git"
  - prefix: "src/Instrumentation/Psr15"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-psr15.git"
  - prefix: "src/Instrumentation/Psr16"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-psr16.git"
  - prefix: "src/Instrumentation/Psr18"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-psr18.git"
  - prefix: "src/Instrumentation/Slim"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-slim.git"
  - prefix: "src/Instrumentation/Symfony"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-symfony.git"
  - prefix: "src/Instrumentation/Wordpress"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-wordpress.git"
  - prefix: "src/Instrumentation/CakePHP"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-cakephp.git"
  - prefix: "src/Instrumentation/Yii"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-yii.git"
  - prefix: "src/Context/Swoole"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/context-swoole.git"
  - prefix: "src/AutoInstrumentationInstaller"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-instrumentation-installer.git"
  - prefix: "src/Logs/Monolog"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-logger-monolog.git"
  - prefix: "src/Propagation/ServerTiming"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-propagator-server-timing.git"
  - prefix: "src/Propagation/TraceResponse"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-propagator-traceresponse.git"
  - prefix: "src/ResourceDetectors/Azure"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-detector-azure.git"
  - prefix: "src/ResourceDetectors/Container"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-detector-container.git"
  - prefix: "src/Shims/OpenTracing"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-shim-opentracing.git"
# List of references to split (defined as regexp)
origins:
  - ^main$
  - ^split$
