# Path to a cache directory Used to speed up the split over time by reusing git's objects
cache_url: "/cache/gitsplit"

# Path to the repository to split (default = current path)
project_url: "https://github.com/open-telemetry/opentelemetry-php-contrib.git"

# List of splits.
splits:
  - prefix: "src/MetaPackages/opentelemetry"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/opentelemetry-meta.git"
  - prefix: "src/Aws"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-aws.git"
  - prefix: "src/Symfony"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-sdk-bundle.git"
  - prefix: "src/Instrumentation/HttpAsyncClient"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-http-async.git"
  - prefix: "src/Instrumentation/IO"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-io.git"
  - prefix: "src/Instrumentation/Laravel"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-laravel.git"
  - prefix: "src/Instrumentation/PDO"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-pdo.git"
  - prefix: "src/Instrumentation/Psr15"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-psr15.git"
  - prefix: "src/Instrumentation/Psr18"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-psr18.git"
  - prefix: "src/Instrumentation/Slim"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-slim.git"
  - prefix: "src/Instrumentation/Symfony"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-symfony.git"
  - prefix: "src/Instrumentation/Wordpress"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-auto-wordpress.git"
  - prefix: "src/Context/Swoole"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/context-swoole.git"
  - prefix: "src/AutoInstrumentationInstaller"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-instrumentation-installer.git"
  - prefix: "src/Logs/Monolog"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-logger-monolog.git"
  - prefix: "src/Propagation/TraceResponse"
    target: "https://${GH_TOKEN}@github.com/opentelemetry-php/contrib-propagator-traceresponse.git"

# List of references to split (defined as regexp)
origins:
  - ^main$
  - ^split$
