name: Contrib CI Pipeline
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  CI:
    uses: open-telemetry/opentelemetry-php-contrib/.github/workflows/instrumentation-curl.yml@b7bc976ebc81c1cd5c3abb9077be5072a791e8f2 # main
    with:
      package-root: '.'
