name: Contrib CI Pipeline
on:
  workflow_dispatch:

jobs:
  CI:
    uses: open-telemetry/opentelemetry-php-contrib/.github/workflows/instrumentation-ext-rdkafka.yml@176b3fc537e89c8e718f2a259f4bbf1772b25545 # main
    with:
      package-root: '.'
