name: Contrib CI Pipeline
on:
  workflow_dispatch:

jobs:
  CI:
    uses: open-telemetry/opentelemetry-php-contrib/.github/workflows/instrumentation-ext-rdkafka.yml@b7bc976ebc81c1cd5c3abb9077be5072a791e8f2 # main
    with:
      package-root: '.'
