receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  logging:
    loglevel: debug
  awsxray:
    region: 'us-west-2'
    sending_queue:
      batch:

  awsemf:
    region: 'us-west-2'
    sending_queue:
      batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      exporters: [awsemf]

  telemetry:
    logs:
      level: debug
