name: Contrib CI Pipeline
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  CI:
    uses: open-telemetry/opentelemetry-php-contrib/.github/workflows/instrumentation-mysqli.yml@1835f286bd580bb2813b710d69e727f8ff7237c5 # main
    with:
      package-root: '.'
