name: Contrib CI Pipeline
on:
  workflow_dispatch:

jobs:
  CI:
    uses: ChrisLightfootWild/opentelemetry-php-contrib/.github/workflows/instrumentation-mysqli.yml@poc/shared-ci
    with:
      package-root: '.'
