name: Contrib CI Pipeline
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  CI:
    uses: open-telemetry/opentelemetry-php-contrib/.github/workflows/metrics-runtime.yml@c14ae6434d3788fa703749844d824ecb9eb0ce8b # main
    with:
      package-root: '.'
