name: Contrib CI Pipeline
on:
  workflow_dispatch:

jobs:
  CI:
    uses: open-telemetry/opentelemetry-php-contrib/.github/workflows/metrics-runtime.yml@03b5f937fb52995080ca2a94e7b3ea790cc470d5 # main
    with:
      package-root: '.'
