FROM busybox@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616

# glibc (Debian) builds
COPY --from=build-non-zts-81    /build /autoinstrumentation/20210902
COPY --from=build-zts-81        /build /autoinstrumentation/20210902
COPY --from=build-non-zts-82    /build /autoinstrumentation/20220829
COPY --from=build-zts-82        /build /autoinstrumentation/20220829
COPY --from=build-non-zts-83    /build /autoinstrumentation/20230831
COPY --from=build-zts-83        /build /autoinstrumentation/20230831
COPY --from=build-non-zts-84    /build /autoinstrumentation/20240924
COPY --from=build-zts-84        /build /autoinstrumentation/20240924
COPY --from=build-non-zts-85    /build /autoinstrumentation/20250925
COPY --from=build-zts-85        /build /autoinstrumentation/20250925

# musl (Alpine) builds
COPY --from=build-non-zts-musl-81   /build /autoinstrumentation/20210902
COPY --from=build-zts-musl-81       /build /autoinstrumentation/20210902
COPY --from=build-non-zts-musl-82   /build /autoinstrumentation/20220829
COPY --from=build-zts-musl-82       /build /autoinstrumentation/20220829
COPY --from=build-non-zts-musl-83   /build /autoinstrumentation/20230831
COPY --from=build-zts-musl-83       /build /autoinstrumentation/20230831
COPY --from=build-non-zts-musl-84   /build /autoinstrumentation/20240924
COPY --from=build-zts-musl-84       /build /autoinstrumentation/20240924
COPY --from=build-non-zts-musl-85   /build /autoinstrumentation/20250925
COPY --from=build-zts-musl-85       /build /autoinstrumentation/20250925

COPY opentelemetry.ini /autoinstrumentation/opentelemetry.ini

RUN chmod -R go+r /autoinstrumentation
