name: Contrib CI Pipeline
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  CI:
    uses: open-telemetry/opentelemetry-php-contrib/.github/workflows/instrumentation-laravel.yml@4f68ecb9760605760d991360df23c6cdeee7dab4 # main
    with:
      package-root: '.'
