name: Contrib CI Pipeline
on:
  workflow_dispatch:

jobs:
  CI:
    uses: open-telemetry/opentelemetry-php-contrib/.github/workflows/instrumentation-laravel.yml@main
    with:
      package-root: '.'
